# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# # Run migrations and collect static files
# RUN python manage.py makemigrations && python manage.py migrate --noinput

# Run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]